sudo: required
language: bash
services:
  - docker
env:
  global:
    - CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=True
before_deploy:
  # Authorize with gcloud
  - echo $GCLOUD_ENCODED_CREDS | base64 -d > /tmp/gcloud.json
  - gcloud auth activate-service-account $(jq -r ".client_email" /tmp/gcloud.json) --key-file=/tmp/gcloud.json
  - >
    if [[ -n "$TRAVIS_TAG" ]] ; then
      gcloud container clusters get-credentials production --project=commercial-tribe --zone=us-east1-c;
    else
      gcloud container clusters get-credentials staging --project=commercial-tribe-staging --zone=us-central1-a;
    fi

  # Install and configure kubectl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
deploy:
  - provider: script
    script: ./build-and-push.sh
    on:
      all_branches: true
  - provider: script
    script: ./deploy.sh gke_commercial-tribe-staging_us-central1-a_staging staging
    on:
      branch: master
  - provider: script
    script: ./deploy.sh gke_commercial-tribe_us-east1-c_production production
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v20[0-9]{2}\.[1-4]\.[1-6]\.[0-9]+$
